__name__ = 'chromexup'
__version__ = '0.4.4'
__description__ = 'External extension updater for Chromium based browsers'
__url__ = 'https://github.com/xsmile/chromexup'
__author__ = 'xsmile'
__author_email__ = '<>'
__license__ = 'MIT'
